<html>
<head>
</head>
<body>
<table width="728">
<tr>
	<td>
	<table>
		<tr><td colspan="5" align="center"><span style="background:#000; color:#FFFFFF; border-radius:8px; padding:2px;">Impactools</span></td></tr>
		<tr><td colspan="5" align="left"><span style="color:#FF0000;">Maintenance / Automotive Impactools™</span></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">1/4" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-4-drive/2101k" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2101K-300_MiniImpact_p001_m.jpg" alt="" height="90" width="70" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2101K </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-4-drive/2101xp" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/2101k_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2101XP </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-4-drive/2101xp-qc" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2101XP_QC_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2101XP-QC </span></td>
		<!--<td align="center"><a href="http://www.ingersollrandproducts.com/am-en/products/air/compressed-air-treatment/non-cycling-refrigerated-dryers/102-380-m3-min-3600-13-420-cfm" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/NEW_19_36000_13420cfm_Non_Cycling_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 102-380m3/min, 3600-13420cfm </span></td>
		<td align="center"><a href="http://www.ingersollrandproducts.com/am-en/products/air/compressed-air-treatment/non-cycling-refrigerated-dryers/high-inlet-temp-0_42-3-m3-min-15-100-cfm" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/NEW_20_High_Temp_Non_Cycling_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> High Inlet Temp </span></td>-->
		</tr>
		<tr><td colspan="5"><hr /></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">3/8" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-8-drive/2115timax-series" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2115_timax-009609_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2015MAX 3/8 Impact Wrench </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-8-drive/2102xp" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/2102XP_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2102XP </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-8-drive/2015max-3-8-impact-wrench" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2015_render_LRweb_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2115TiMAX Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-8-drive/211" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/211_IMPACTOOL_HR_PRODUCT_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 211 </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-8-drive/212" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/212_IMPACTOOL_HR_PRODUCT_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 212 </span></td>
		</tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-8-drive/216b" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/216B_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 216B </span></td>
		</tr>
		<tr><td colspan="5"><hr /></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">1/2" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/2135qxpa_series" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2135QXPA_Impact_la_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2135QXPA Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/2235-Series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/2235QTiMAX_Impact_la_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2235 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/2135timax-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2135_COB_HiRes_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2135TiMAX Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/2025max" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2025_render_LRweb_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2025MAX </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/2350xp" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2135XP_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2350XP </span></td>
		</tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/2130-series" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2130_HR_04_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2130 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/231-series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/231C_HR_PRODUCT_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 231 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/244a-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/244A_HR_PRODUCT_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 244A Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/236" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/236_Impact_p004_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 236 </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-2-drive/232tgsl-thunder-gun-street-legal" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/232TGSL_STREETLEGAL_P001_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 232TGSL Thunder Gun Street Legal™ </span></td>
		</tr>
		<tr><td colspan="5"><hr /></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">3/4" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-4-drive/2145QiMAX-Impactool" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2145QiMAX_Angle_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2145QiMAX </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-4-drive/2161xp-series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/2161xp_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2161XP Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-4-drive/261-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/261_Impact_p001_web_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 261 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/3-4-drive/259" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/259_profile_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 259 </span></td>
		</tr>
		<tr><td colspan="5"><hr /></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">1" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-drive/2155QiMAX-Impactool" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2155QiMAX_impactool_web(1)_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2155QiMAX Impact Wrench </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-drive/2190ti-series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/2190Ti_DTi_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2190Ti Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-drive/293-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/293_IMPACTOOLHR_PRODUCT_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 293 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-drive/280-290-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/280_290_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 280/290 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-drive/2171xp" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2171XP_HR_PRODUCT_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2171XP </span></td>
		</tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-drive/285b-295a-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/285B_6_295a_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 285B/295A Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/maintenance-automotive-impactools/1-drive/271" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/271_IMPACTOOL_HR_PRODUCT_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 271 </span></td>
		</tr>
		<tr><td><hr /></td></tr>
		<tr><td colspan="5" align="left"><span style="color:#FF0000;">Industrial Production Impactools™</span></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">3/8" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/3-8-drive/2900-series" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2902P1_M.jpeg" alt="" height="90" width="70" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2900 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/3-8-drive/1700-series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/1702SB1_M.jpeg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 1700 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/3-8-drive/max-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2115_Ptimax-009609_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> MAX Series </span></td>
		</tr>
		<tr><td colspan="5"><hr /></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">1/2" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-2-drive/2900-series" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2906P1_Impactool_web_l_thumb.jpg" alt="" height="90" width="70" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2900 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-2-drive/2700-series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/2705P1_5FImpact_5Fp002_2Ejpg_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2700 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-2-drive/max-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2135PTiMAX_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> MAX Series </span></td>
		</tr>
		<tr><td colspan="5"><hr /></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">3/4" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/3-4-drive/2900-series" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2920B1_impactool_web_l_thumb.jpg" alt="" height="90" width="70" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2900 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/3-4-drive/2900-titanium-series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/2925P1Ti_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2900 Titanium Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/3-4-drive/1700-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/1720P1_Impactool_p002_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 1700 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/3-4-drive/2100-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2141P_IMPACTOOL_P001_m.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2100 Series </span></td>
		</tr>
		<tr><td colspan="5"><hr /></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">1" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-drive/2900-series" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2934P2_M.jpeg" alt="" height="90" width="70" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2900 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-drive/2900-titanium-series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/2925Ti_5FImpactool_5Fp002_2Ejpg_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2900 Titanium Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-drive/3900-titanium-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/3900_5FImpactThunderbolt_5Fp001_2Ejpg_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 3900 Titanium Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-drive/1700-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/1712B2_M.jpeg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 1700 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-drive/2100-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/2141PSP_l_thumb.jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2100 Series </span></td>
		</tr>
		<tr><td colspan="5"><hr /></td></tr>
		<tr><td colspan="5" align="center"><span style="color:#0000FF;">1-1/2" - 2-1/2" Drive</span></td></tr>
		<tr>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-1-2-3-1-2-drive/2900-series" rel="example2" title="TS4N5 Two-Stage" target="_blank"><img src="Contents/2950B7_m.jpeg" alt="" height="90" width="70" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 2900 Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-1-2-3-1-2-drive/titanium-series" rel="example2" title="4-37kW/5-50hp" target="_blank"><img src="Contents/3900_5FImpactThunderbolt_5Fp001_2Ejpg_l_thumb (1).jpg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> Titanium Series </span></td>
		<td align="center" width="20%"><a href="http://www.ingersollrandproducts.com/am-en/products/tools/impactools/industrial-production-impactools/1-1-2-3-1-2-drive/5000-series" rel="example2" title="Electric-Driven Single Stage" target="_blank"><img src="Contents/599A1_m.jpeg" alt="" height="120" width="100" /></a><br /><span style="background:#0099FF; color:#FFFFFF; border-radius:8px; padding:2px; font-size:10px;"> 5000 Series </span></td>
		</tr>
		
		
	</table>
	</td>
	</tr>

</table>
</body>
</html>